LOCAL_PATH := device/lge/c70n

USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lge/c70n/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := msm8916
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_USES_QCOM_HARDWARE := true

TARGET_BOOTLOADER_BOARD_NAME := c70n

TARGET_KERNEL_CONFIG := c70n_global_com_defconfig
TARGET_KERNEL_SOURCE := kernel/lge/h440n/
TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/kernel

TARGET_NO_BOOTLOADER := true

BOARD_CUSTOM_BOOTIMG := true
BOARD_CUSTOM_BOOTIMG_MK := $(LOCAL_PATH)/mkbootimg.mk

BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=c70n user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci lpm_levels.sleep_disabled=1 vmalloc=508m
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_SEPARATED_DT := true
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_DT_SIZE := 178176
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x02000000 --tags_offset 0x00000100

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x01800000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x01800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x99999a00
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0xe47e6200
BOARD_FLASH_BLOCK_SIZE := 131072


# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/fstab.c70n
TARGET_RECOVERY_INITRC := $(LOCAL_PATH)/init.recovery.c70n.rc
